Added 5 points Prediction and CSS
ContriHUB/Graph-Analyzer pull request #7
Opened 2024-10-21 21:37 UTC by aachintya

## Description

1. **Implemented Next 5 Points Prediction:** Added a feature that predicts the next five data points using a regression model, enhancing the predictive capabilities of the application.

2. **CSS Addition and Fixes:** Addressed the missing CSS issue by incorporating the intended styles, improving the overall look and feel of the interface.

3. Updated the README.md and fixed the requirements.txt which was missing many dependencies.

## Related Issue

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Motivation and Context

A good CSS is always good to make the project appealing and other was the listed Issue #1 

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Screenshots (if appropriate):

https://github.com/user-attachments/assets/e8f7d5b4-6348-40f9-b703-807d95f71322

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

2024-10-21 21:38 UTC, aachintya commented
Even though the issue for frontend was closed, project was missing any CSS styling so i made it.

2024-10-22 09:43 UTC, Nandika-A commented
@aachintya revert the css changes and anything you have done additionally except completing the function for prediction. You should ask before addressing anything not mentioned in the issue.

2024-10-22 10:53 UTC, Nandika-A commented
> Even though the issue for frontend was closed, project was missing any CSS styling so i made it.

Because they are in another branch.

2024-10-22 12:15 UTC, aachintya commented
Ok mam. Apologies. I'll revert it

2024-10-22 14:04 UTC, aachintya commented
Here is the updated work.

<img width="1511" alt="Screenshot 2024-10-22 at 7 30 22 PM" src="https://github.com/user-attachments/assets/8ecfc288-12ff-439b-b626-8b78b96a8d1e">

2024-10-23 20:07 UTC, aachintya commented
Added this as per my assigned issue #3 

<img width="268" alt="Screenshot 2024-10-24 at 1 36 31 AM" src="https://github.com/user-attachments/assets/547d10e7-b986-4bed-969f-507cfc2f44a4">

2024-10-24 08:43 UTC, Nandika-A commented
> Added this as per my assigned issue #3 
> 
> <img width="268" alt="Screenshot 2024-10-24 at 1 36 31 AM" src="https://github.com/user-attachments/assets/547d10e7-b986-4bed-969f-507cfc2f44a4">
> 
> 
> 

Make changes as per the reviews for your first issue. The third one seems fine to me.

2024-10-24 08:57 UTC, aachintya commented
> Make changes as per the reviews for your first issue. The third one seems fine to me.

Yes mam i did the changes for the first 
The time was about to get over the 3rd issue thats why i added it 
Can u review and tell what more i can do?

2024-10-24 11:15 UTC, Nandika-A commented
> > Make changes as per the reviews for your first issue. The third one seems fine to me.
> 
> Yes mam i did the changes for the first 
> The time was about to get over the 3rd issue thats why i added it 
> Can u review and tell what more i can do or is it fine?

Third one seems fine

2024-10-24 11:30 UTC, aachintya commented
> > > Make changes as per the reviews for your first issue. The third one seems fine to me.
> > 
> > 
> > Yes mam i did the changes for the first
> > The time was about to get over the 3rd issue thats why i added it
> > Can u review and tell what more i can do or is it fine?
> 
> Third one seems fine

OK mam thank you.

2024-10-27 04:13 UTC, Nandika-A commented
@aachintya are you making the changes as per the reviews?

2024-10-27 04:42 UTC, aachintya commented
> @aachintya are you making the changes as per the reviews?

Yes mam i did the changes already.
I removed the css and other unncessary changes

2024-10-27 06:55 UTC, Nandika-A commented
> > @aachintya are you making the changes as per the reviews?
> 
> Yes mam i did the changes already.
> I removed the css and other unncessary changes

@aachintya not these, migrate to the files tab and check the reviews on the code.

2024-10-27 07:18 UTC, aachintya commented
> > > @aachintya are you making the changes as per the reviews?
> > 
> > 
> > Yes mam i did the changes already.
> > I removed the css and other unncessary changes
> 
> @aachintya not these, migrate to the files tab and check the reviews on the code.

<img width="169" alt="Screenshot 2024-10-27 at 12 46 41 PM" src="https://github.com/user-attachments/assets/e8c5ca3b-2ec1-465d-92a7-a79000d45e15">

Could you please explain me. i couldn't find any code reviews on the files changed tab.

2024-10-27 08:24 UTC, Nandika-A commented
@aachintya https://github.com/ContriHUB/Graph-Analyzer/pull/7#pullrequestreview-2387178130 this is the link to the code reviews.

2024-10-27 09:17 UTC, aachintya commented
> @aachintya [#7 (review)](https://github.com/ContriHUB/Graph-Analyzer/pull/7#pullrequestreview-2387178130) this is the link to the code reviews.

link is not opening. i am not able to see any comments out there.

2024-10-27 18:51 UTC, Nandika-A commented
> > @aachintya [#7 (review)](https://github.com/ContriHUB/Graph-Analyzer/pull/7#pullrequestreview-2387178130) this is the link to the code reviews.
> 
> link is not opening. i am not able to see any comments out there.

Try this link: https://github.com/ContriHUB/Graph-Analyzer/pull/7/files#diff-c2aec32f1841f40dd9d56c7e2640bd934d497509e76dd14caf1818c6643de1d9R22
![image](https://github.com/user-attachments/assets/a647da9b-b53a-405f-a466-bfbd7611d5d5)
this is in files changed tab. You must have also received it's email.

2024-10-27 19:16 UTC, aachintya commented
> > > @aachintya [#7 (review)](https://github.com/ContriHUB/Graph-Analyzer/pull/7#pullrequestreview-2387178130) this is the link to the code reviews.
> > 
> > 
> > link is not opening. i am not able to see any comments out there.
> 
> Try this link: https://github.com/ContriHUB/Graph-Analyzer/pull/7/files#diff-c2aec32f1841f40dd9d56c7e2640bd934d497509e76dd14caf1818c6643de1d9R22 ![image](https://private-user-images.githubusercontent.com/93462818/380523191-a647da9b-b53a-405f-a466-bfbd7611d5d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNTY0NTgsIm5iZiI6MTczMDA1NjE1OCwicGF0aCI6Ii85MzQ2MjgxOC8zODA1MjMxOTEtYTY0N2RhOWItYjUzYS00MDVmLWE0NjYtYmZiZDc2MTFkNWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDE5MDkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MmIxNDBiOGNiNGUyNmYxOGU0YTU1MmFjMmE1YTZjNTM3NGFjMmFkOTBmMzFmN2EyOTY0MjA2Y2I3OGUzOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pZd6Bqb7YNMICbCBA1eLry9_STNnQxmxkRi0D_2ZfU0) this is in files changed tab. You must have also received it's email.

Thank you mam. i'll work upon them. 
i was unable to see the reviews or get any notification because they are still pending and will not be visible to others unless published  😅
[i checked on this youtube video ](https://youtu.be/lSnbOtw4izI?si=IAjc49Yk9Ai8z7mv&t=133)

2024-10-28 15:51 UTC, Nandika-A requested changes

2024-10-28 15:51 UTC, Nandika-A commented on analyzer/extract_graph_data.py
> +def predict_next_points(data_points, num_predictions=5):
It is very less likely that the graph the user uploads is linear. So use polynomial regression instead of linear. You can directly use the model from sklearn library.

2024-10-28 15:51 UTC, Nandika-A commented on analyzer/extract_graph_data.py
> +def predict_next_points(data_points, num_predictions=5):
So one of the ways can be using ML and fitting the model with current x and y, and predicting the values of y for next 5 x using the trained model.

2024-10-28 15:51 UTC, Nandika-A commented on analyzer/extract_graph_data.py
> +def predict_next_points(data_points, num_predictions=5):
@aachintya since this dataset would be very small, you can directly use the model in the same function instead of creating the model image.

2024-10-29 05:31 UTC, aachintya commented
I did the changes.

2024-10-29 07:44 UTC, Nandika-A approved these changes

2024-10-29 07:45 UTC, merged